# Generated by Django 4.2.3 on 2023-08-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_orderedpizza_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedpizza',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.orderhistory'),
        ),
    ]
