# Generated by Django 4.2.3 on 2023-08-26 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizzeria', '0002_remove_category_code_remove_pizza_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
