# Generated by Django 4.2.3 on 2023-08-26 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_alter_ordersession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_currency',
        ),
    ]
