# Generated by Django 4.2.3 on 2023-08-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_remove_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order_session', 'pizza'), name='unique pizza'),
        ),
    ]
