# Generated by Django 4.2.3 on 2023-08-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0008_alter_orderitem_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='max_selection',
            new_name='required_amount',
        ),
    ]
